ViewModels/EnderecoViewModel.cs
using DigitalStore.Models;

namespace DigitalStore.ViewModels
{
    // ViewModel para view Endereco
    // O usuário pode adicionar e escolher endereços de entrega.
    public class EnderecoViewModel
    {
        // Chave do Google API, para esconder a chvae no link da view
        public string? GoogleApiKey { get; set; }

        // ID do usuário logado.
        public int UsuarioId { get; set; }

        // Para adicionar um endereco
        public EnderecoModel? Endereco { get; set; }

        // Lista de endereços cadastrados pelo usuário para escolha na finalização da compra
        public List<EnderecoModel> Enderecos { get; set; } = new List<EnderecoModel>();

    }
}

Controllers/EnderecoController.cs
using DigitalStore.Filters;
using DigitalStore.Helper;
using DigitalStore.Helper.Interfaces;
using DigitalStore.Models;
using DigitalStore.Repositorio.Interfaces;
using DigitalStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DigitalStore.Controllers
{
    /* 
        Controller responsável pela gestão dos endereços de um usuário.
        
        Métodos:
        - Enderecos(int id): Exibe a lista de endereços do usuário e um formulário para adicionar um novo endereço.
        - (POST) AddEndereco(EnderecoModel endereco): Adiciona um novo endereço para o usuário, com verificações de validade.
        - (POST) RemoverEndereco(int id): Remove um endereço baseado no ID do endereço.
    */
    [PaginaCliente]
    public class EnderecoController : Controller
    {
        // Declaração das dependências injetadas no controlador
        private readonly string _googleApiKey;
        private readonly IEnderecoRepositorio _enderecoRepositorio;
        private readonly ISessao _sessao;
        private readonly ILogger<EnderecoController> _logger;  // ILogger para registrar logs de erro e sucesso.

        // Construtor do controlador. Recebe o repositório de endereços e o ILogger como dependências.
        // Adiciona checagem para garantir que as dependências não sejam nulas.
        public EnderecoController(IOptions<GoogleAPISettings> googleApiKey, IEnderecoRepositorio enderecoRepositorio, ISessao sessao, ILogger<EnderecoController> logger)
        {
            _googleApiKey = googleApiKey.Value.ApiKey ?? throw new ArgumentNullException(nameof(googleApiKey.Value.ApiKey));
            _enderecoRepositorio = enderecoRepositorio ?? throw new ArgumentNullException(nameof(enderecoRepositorio));
            _sessao = sessao ?? throw new ArgumentNullException(nameof(sessao));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        // Método GET para exibir os endereços do usuário e o formulário de adicionar um novo endereço.
        [HttpGet]
        public async Task<IActionResult> Enderecos()
        {
            try
            {
                // Busca a sessão do usuário logado.
                var usuario = _sessao.BuscarSessaoDoUsuario();
                if (usuario == null)
                {
                    throw new ArgumentException("Sessao do usuário é nula");
                }

                // Busca todos os endereços do usuário a partir do repositório.
                var enderecos = await _enderecoRepositorio.BuscarTodosOsEnderecosDoUsuarioAsync(usuario.UsuarioId);

                // Criação de um modelo de endereço vazio para preenchimento na view.
                var endereco = new EnderecoModel
                {
                    UsuarioId = usuario.UsuarioId,
                    EnderecoCompleto = string.Empty
                };

                // Criação do ViewModel com os dados do usuário e os endereços obtidos.
                var viewModel = new EnderecoViewModel
                {
                    GoogleApiKey = _googleApiKey,
                    UsuarioId = usuario.UsuarioId,
                    Enderecos = enderecos,
                    Endereco = endereco
                };

                return View(viewModel); // Retorna a view com o ViewModel contendo os dados
            }
            catch (Exception ex)
            {
                // Lida com qualquer outra exceção inesperada.
                _logger.LogError(ex, "Erro ao acessar os endereços do usuário.");
                TempData["Alerta"] = "Ocorreu um erro ao tentar acessar seus endereços. Tente novamente mais tarde.";
                return RedirectToAction("Index", "Home");
            }
        }

        // Método POST para adicionar um novo endereço.
        [HttpPost]
        public async Task<IActionResult> AddEndereco(EnderecoModel endereco)
        {
            try
            {
                // Valida o modelo de dados do endereço.
                if (ModelState.IsValid)
                {
                    // Verifica se o número de endereços já cadastrados pelo usuário não excede o limite.
                    var enderecosLimite = await _enderecoRepositorio.BuscarTodosOsEnderecosDoUsuarioAsync(endereco.UsuarioId);
                    if (enderecosLimite.Count >= 4)  // Limite de endereços por usuário
                    {
                        TempData["Alerta"] = "Você só pode ter no máximo 4 endereços cadastrados.";
                        return Redirect(Request.Headers["Referer"].ToString()); // Redireciona para a página anterior
                    }

                    // Adiciona o novo endereço ao repositório.
                    await _enderecoRepositorio.AddEnderecoAsync(endereco);
                    _logger.LogInformation($"Endereço adicionado com sucesso para o usuário {endereco.UsuarioId}."); // Loga a operação de sucesso
                    TempData["Alerta"] = "Endereço adicionado com sucesso!";
                    return Redirect(Request.Headers["Referer"].ToString()); // Redireciona para a página anterior
                }

                // Caso o modelo não seja válido, registra o erro de validação e redireciona para a página anterior.
                TempData["Alerta"] = "Houve um erro ao adicionar o endereço, verifique os dados inseridos.";
                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (Exception ex)
            {
                // Captura exceções inesperadas e registra o erro.
                _logger.LogError(ex, "Erro ao adicionar o endereço.");
                //TempData["Alerta"] = "Ocorreu um erro ao tentar adicionar o endereço, tente novamente.";
                TempData["Alerta"] = $"Erro: {ex.Message}";
                return Redirect(Request.Headers["Referer"].ToString()); // Redireciona para a página anterior
            }
        }

        // Método POST para remover um endereço.
        [HttpPost]
        public async Task<IActionResult> RemoverEndereco(int id)
        {
            try
            {
                // Valida se o ID do endereço é válido. Se não for, lança uma exceção.
                if (id <= 0)
                {
                    throw new ArgumentException("ID do endereço inválido.");
                }

                // Remove o endereço do repositório, caso o ID seja válido.
                await _enderecoRepositorio.RemoverEnderecoAsync(id);
                _logger.LogInformation($"Endereço {id} removido com sucesso."); // Loga a operação de sucesso
                TempData["Alerta"] = "Endereço removido com sucesso!";
                return Redirect(Request.Headers["Referer"].ToString()); // Redireciona para a página anterior após remoção
            }
            catch (Exception ex)
            {
                // Captura exceções inesperadas e registra o erro.
                _logger.LogError(ex, "Erro ao remover o endereço.");
                TempData["Alerta"] = "Ocorreu um erro ao tentar remover o endereço.";
                return Redirect(Request.Headers["Referer"].ToString()); // Redireciona para a página anterior após erro
            }
        }
    }
}

Views/Endereco/Enderecos.cshtml
@model EnderecoViewModel

@{
    ViewData["Title"] = "Endereços";
}

<div class="container my-5">
    <div class="row">
        <!-- Sidebar Left -->
        <div class="col-md-3">
            <div class="card shadow-sm border-0 rounded-3">
                <div class="card-body p-3">
                    <ul class="list-unstyled">
                        <li><a asp-controller="Usuario" asp-action="MinhaConta" asp-route-id="@Model.UsuarioId" class="text-decoration-none text-dark fw-bold d-block py-2"><i class="bi bi-person"></i> Meus Dados</a></li>
                        <hr>
                        <li><a asp-controller="Pedido" asp-action="MeusPedidos" asp-route-id="@Model.UsuarioId" class="text-decoration-none text-dark fw-bold d-block py-2"><i class="bi bi-list"></i> Meus Pedidos</a></li>
                        <hr>
                        <li><a asp-controller="Endereco" asp-action="Enderecos"  class="text-decoration-none text-dark fw-bold d-block py-2"><i class="bi bi-box-seam"></i> Endereços</a></li>
                        <hr>
                        <li><a asp-controller="AlterarSenha" asp-action="AlterarSenha" asp-route-id="@Model.UsuarioId" class="text-decoration-none text-dark fw-bold d-block py-2"><i class="bi bi-lock"></i> Alterar Senha</a></li>
                        <hr>
                                               <li>
                            <a class="text-decoration-none text-dark fw-bold d-block py-2" asp-controller="Login" asp-action="Sair">
                                <i class="bi bi-box-arrow-right"></i> Sair
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Main Content: User Data -->
        <div class="col-md-9">
            <!-- Card Principal -->
            <div class="card shadow-sm mb-4 mt-2">
                <div class="card-header bg-dark text-white">
                    <h5 class="mb-0">Endereços</h5>
                </div>
                <div class="card-body">
                    <!-- Conteúdo Condicional -->
                    @if (Model.Enderecos != null && Model.Enderecos.Any())
                    {
                        @foreach (var endereco in Model.Enderecos)
                        {
                            <div class="d-flex justify-content-between mb-1 align-items-start">
                                <!-- Exibe a lista de endereços do usuário com radio buttons para selecionar o endereço de envio -->
                                <div class="form-check">
                                    <input class="form-check-input" type="hidden" name="EnderecoId" value="@endereco.EnderecoId" id="endereco_@endereco.EnderecoId" />
                                    <label class="form-check-label" for="endereco_@endereco.EnderecoId">
                                        <p>@endereco.EnderecoCompleto</p>
                                    </label>
                                </div>

                                <!-- Formulário para remover o endereço -->
                                <form asp-controller="Endereco" asp-action="RemoverEndereco" method="post" style="display:inline;">
                                    <input type="hidden" name="id" value="@endereco.EnderecoId" />
                                    <button type="submit" class="btn btn-link text-dark" title="Remover Endereço">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        }
                    }
                    else
                    {
                        <p class="text-center text-muted">Você ainda não possui endereços cadastrados.</p>
                    }

                    <!-- Formulário para Adicionar Novo Endereço -->
                    <div class="mt-1">
                        <h6 class="card-title">Adicionar Novo Endereço</h6>
                        <form asp-controller="Endereco" asp-action="AddEndereco" method="post">
                            <input type="hidden" name="UsuarioId" value="@Model.Endereco.UsuarioId" />
                            <div class="form-floating mb-2">
                                <input class="form-control" type="text" name="EnderecoCompleto" id="endereco" asp-for="@Model.Endereco.EnderecoCompleto" placeholder="Digite o endereço completo" required />
                                <label for="EnderecoCompleto">Endereço Completo</label>
                            </div>

                            <div class="mt-1 d-flex justify-content-end">
                                <button type="submit" class="btn btn-outline-dark btn-sm">Adicionar Endereço</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        var googleApiKey = '@Model?.GoogleApiKey'; // Chave da API do Google
               var script = document.createElement('script');
               script.src = `https://maps.googleapis.com/maps/api/js?key=${googleApiKey}&libraries=places&callback=initAutocomplete`;
               script.async = true;
               script.defer = true;
               document.head.appendChild(script);
    </script>    
    <script src="~/js/google-api-endereco.js"></script>
}